#! /bin/bash

beamer_state="standby"
prev_beamer_state="standby"

BEAMER_ON="on"
BEAMER_OFF="standby"

while true; do

    beamer_state=$(echo pow 0 | cec-client -s -d 1 | grep -oP '(?<=power status: ).*')

    if [[ "$beamer_state" == "$BEAMER_OFF" && "$prev_beamer_state" == "$BEAMER_ON" ]]; then

        echo "Shutting down Pi now"
        sudo reboot now
        #sudo shutdown -h now
        break

    else
        if [[ "$beamer_state" == "$BEAMER_OFF" || "$beamer_state" == "$BEAMER_ON" ]]; then
            prev_beamer_state="$beamer_state"
        fi

        echo "$beamer_state"
        sleep 10
    fi
done
