#! /bin/bash


if [[ $# < 1 ]]; then
	echo "give ip adress of pi"
	exit

else
    IP=$1

	scp ./detect_shutdown ./play_snoezel pi@"$IP":/home/pi/projecten/snoezelfilm
    # scp ./rc.local pi@"$IP":/etc
    # scp ./asound.conf pi@"$IP":/home/pi/
    # scp ./fstab pi@"$IP":/home/pi/
fi
